### ISSUE TITLE
Basic User : Login : Access App

### ISSUE THREAD

**Issue by ahijaouy** [ahijaouy/CS2340#10]
**Title**: As a basic user I want to be able to login to the app with my username and password so that I can gain access to the app's core features. 
 
**Tasks**:
- [x] Add text boxes for username and password and a sign in button
- [x] Implement a hardcoded login logic check
- [x] Implement a home page with a logout button

**Acceptance Scenarios**:
- [x] GIVEN a basic user opens the app, WHEN the user enters valid login credentials in the user and password fields and clicks the login button, THEN they should be taken to the home screen.

- [x] GIVEN a basic user opens the app, WHEN the user enters invalid login credentials in the user and password fields and clicks the login button, THEN they should stay on the login screen and be prompted to enter valid credentials.

- [x] GIVEN a basic user has successfully logged in , WHEN the user clicks the logout button, THEN they should be taken to the login screen

**Done Done Criteria**
- [ ] Unit Tests Updated
- [x] Pushed to master
- [x] Put in Closed Box
