### ISSUE TITLE
Unregistered User : Register new account : Get login credentials for app

### ISSUE THREAD

**Issue by ahijaouy** [ahijaouy/CS2340#19]

**Comment by gabrielnan** [comment]
As an unregistered user, I want to be able to register a new account, so that I can gain login credentials for the app.

**Tasks:**
- [ ] create new activity
- [ ] add username, password, and confirm password text fields to view
- [ ] create register and sign in buttons
- [ ] use Auth0 to validate and create username and password

**Acceptance Scenarios:**
- [ ] GIVEN an unregistered user is on the login screen, WHEN the unregistered user clicks the register button, THEN the unregistered user should be brought to the registration activity.
- [ ] GIVEN an unregistered user is on the registration view, WHEN the unregistered user enters invalid username or password, THEN the model is unchanged and error message is displayed.
- [ ] GIVEN an unregistered user is on the registration screen, WHEN a valid username and password is entered, THEN the model should add this basic user.

**Done Done Criteria:**
- [ ] Unit tests are written and passed to ensure correct user success and failure registration.
- [ ] Corresponding feature branches are merged to master branch.
