### ISSUE TITLE
Basic User : Update Account Info : Change personal information 

### ISSUE THREAD

**Issue by ahijaouy** [ahijaouy/CS2340#20]

**Comment by walkman1915** [comment]
**Title:** As a basic user, I want to be able to update my account info, so that I can change personal information like my email address or username.

**Task:**
- [ ] make changes to basic user class
- [ ] make changes to login credentials class 
- [ ] implement changes in controller/activity

**Acceptance Scenarios:**
- [ ] GIVEN a basic user is viewing the changer personal information page, WHEN the basic user enters a valid new email and hits the enter button, THEN the basic user's email is updated in the model and shown in the list of basic users. 
- [ ] GIVEN a basic user is viewing the changer personal information page, WHEN the basic user enters a valid new username and hits the enter button, THEN the basic user's username is updated in the model and shown in the list of basic users. 
- [ ] GIVEN a basic user is editing their personal information, WHEN the basic user hits the back button, THEN the changes are discarded and no changes are made to the model. 
- [ ] GIVEN a basic user is editing their person information, WHEN the basic user tries to enter an invalid email address that does not exist, THEN they are denied updating the their personal information and must start the process over.
- [ ] GIVEN a basic user is editing their personal information, WHEN they enter a username that has already been taken or does not meet the criteria, THEN the user is not able to hit the enter button to submit their personal data. 

**Done Done Criteria:**
- [ ] Unit tests are written or updated to included class standings and are passed
