### ISSUE TITLE
Basic User : Delete Account : Remove self from system 

### ISSUE THREAD

**Issue by ahijaouy** [ahijaouy/CS2340#21]

**Comment by walkman1915** [comment]
As a basic user, I want to be able to delete my accounts, so that I can remove myself from the system if I decide I no longer want to use the app.

**Comment by bengeier** [comment]
As a basic user, I want to be able to delete my account so that I can remove myself from the system if I no longer wish to use the app.

**Tasks:**
- [ ] Add a delete button to the user profile view. 
- [ ] Implement functionality in user class
- [ ] Create a popup that requires the user to log in to delete the account
- [ ] Link to Auth0 to validate log in

**Acceptance Scenarios**
GIVEN: The user is on their profile page WHEN: The user presses the delete account button THEN: the log in validation screen pops up.
GIVEN: The user is on the log in validation screen WHEN: The user enters their username and password and presses enter THEN: their account will be deleted.
GIVEN: The user is on the log in validation screen WHEN: The user enters the wrong username or password and presses enter THEN: The account will not be deleted and the user will be given another try.

**Done Done Criteria**
- [ ] Unit tests updated
- [ ] Changes pushed to master
- [ ] Put in closed box
